CREATE TABLE IF NOT EXISTS pppd (
  id int(11) NOT NULL auto_increment,
  payer_id varchar(60) NOT NULL default '',
  payment_date varchar(50) NOT NULL default '',
  txn_id varchar(50) NOT NULL default '',
  first_name varchar(50) NOT NULL default '',
  last_name varchar(50) NOT NULL default '',
  payer_email varchar(75) NOT NULL default '',
  payer_status varchar(50) NOT NULL default '',
  payment_type varchar(50) NOT NULL default '',
  custom tinytext NOT NULL default '',
  memo tinytext NOT NULL default '',
  item_name varchar(127) NOT NULL default '',
  item_number varchar(127) NOT NULL default '',
  quantity int(11) NOT NULL default '0',
  shipping decimal(9,2) NOT NULL default '0',
  tax decimal(9,2) NOT NULL default '0',
  mc_gross decimal(9,2) NOT NULL default '0',
  mc_fee decimal(9,2) NOT NULL default '0',
  mc_currency varchar(3) NOT NULL default '',
  address_name varchar(255) NOT NULL default '',
  address_street varchar(255) NOT NULL default '',
  address_city varchar(255) NOT NULL default '',
  address_state varchar(255) NOT NULL default '',
  address_zip varchar(20) NOT NULL default '',
  address_country varchar(255) NOT NULL default '',
  address_country_code varchar(10) NOT NULL default '',
  address_status varchar(255) NOT NULL default '',
  contact_phone varchar(20) NOT NULL default '',
  business varchar(255) NOT NULL default '',
  receiver_email varchar(75) NOT NULL default '',
  receiver_id varchar(60) NOT NULL default '',
  residence_country varchar(255) NOT NULL default '',
  shipping_method varchar(255) NOT NULL default '',
  payment_status varchar(255) NOT NULL default '',
  pending_reason varchar(255) NOT NULL default '',
  reason_code varchar(255) NOT NULL default '',
  txn_type varchar(255) NOT NULL default '',
  option_selection1 varchar(255) NOT NULL default '',
  option_selection2 varchar(255) NOT NULL default '',
  option_name1 varchar(255) NOT NULL default '',
  option_name2 varchar(255) NOT NULL default '',
  verify_sign varchar(255) NOT NULL default '',
  notify_version varchar(10) NOT NULL default '',
  mailed int(1) NOT NULL default '0',
  hash varchar(40) NOT NULL default '',
  download_expiration int(11) NOT NULL,
  payment_time int(11) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY txn_id (txn_id),
  UNIQUE KEY hash (hash),
  UNIQUE KEY verify_sign (verify_sign)
) TYPE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS items (
  id int(11) NOT NULL auto_increment,
  item_number varchar(30) NOT NULL default '0',
  item_name varchar(128) NOT NULL default '',
  item_file varchar(256) NOT NULL default '',
  mc_gross decimal(9,2) NOT NULL default 0.00,
  mc_currency enum('USD','CAD','EUR','GBP','JPY') NOT NULL default 'EUR',
  PRIMARY KEY (id),
  UNIQUE KEY item_number (item_number)
) TYPE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
